### ISSUE TITLE
Create an auto-redirect for the profile.jsp using jsp/java

### ISSUE THREAD

**Issue by bradtaniguchi** [bradtaniguchi/GoTorosBank#18]
IF you are not logged in (IE you don't have the httpsession, with a username attribute) and you try to access the profile.jsp page, you should get redirected to the login page. 

Heres some help.
http://stackoverflow.com/questions/20139634/accessing-values-stored-in-httpsession-using-javascript

**Comment by crosby0320** [comment]
just made some changes check it out and let me know i may need to change the popup

**Comment by bradtaniguchi** [comment]
I found another case were we need to redirect the user.
Since the site is a single page app, you can still switch using the user tools on the left if you lose access later.

in the dynamicloader.js can you add a check when you click on any of the buttons?
I used jquery listeners to handle buttons events. Just make a function that checks if the user is logged in, and call that function when the user clicks on any of the user tool buttons.

**Comment by crosby0320** [comment]
Works now it kicks you out on every page switch or JSP page switch we just need to work on the popup look

**Comment by bradtaniguchi** [comment]
I didn't test it until now, and I get kicked out even when I am logged in. 
It seems like the JSP variable inside of the javascript file dynamicLoader.js isn't getting seen correctly. The JSP line <%CODE BLAH%> is just read as a string instead of being checked.

I forgot jsp strings are only checked in a JSP file, I will have to move the code into a <script> tag of a jsp file and access the same variable elsewhere.
