### ISSUE TITLE
FYI: Modal displays deposit amount twice

### ISSUE THREAD

**Issue by Daniel-Hernandez-1** [bradtaniguchi/GoTorosBank#28]
When depositing a valid check, the modal display text shows deposited amount twice in the message:
ex: amount: 7000.0 Amount 7000.0

Not really a bug.

**Comment by bradtaniguchi** [comment]
I will look into it and update it to only show it once.

**Comment by bradtaniguchi** [comment]
Fixed as of this [commit](https://github.com/bradtaniguchi/GoTorosBank/commit/7d6e7ea14b2c8a1f049e2bfe218f3c8bd3aca05c)
