### ISSUE TITLE
FYI: After successful transfer, user is not redirected back to user home page

### ISSUE THREAD

**Issue by Daniel-Hernandez-1** [bradtaniguchi/GoTorosBank#29]
It just stays at the same page. Only mentioning this because other options do return you to the user homepage after successfully completing an action.

**Comment by bradtaniguchi** [comment]
I will look into it and update it, thanks for noticing it

**Comment by bradtaniguchi** [comment]
This is now fixed as of this [commit ](https://github.com/bradtaniguchi/GoTorosBank/commit/4a1484a7111fd78388d6ea809674c448533c67c5)
