### ISSUE TITLE
No Verification that a withdraw was made

### ISSUE THREAD

**Issue by crosby0320** [bradtaniguchi/GoTorosBank#31]
Wen I make a withdraw I don't get an image, i don't see a prompt saying it did the transaction

**Comment by bradtaniguchi** [comment]
Check what it says in the console when you do this. 
Does your account get deducted?

You should get a Modal popup with a box in it and instructions on downloading the image.

**Comment by bradtaniguchi** [comment]
I am closing this, as I believe it was due to the IMSserver not getting updated with the latest version. (I pushed the changes to the IMS Server right now)
