### ISSUE TITLE
Format Issue with payBills Servlet

### ISSUE THREAD

**Issue by bradtaniguchi** [bradtaniguchi/GoTorosBank#6]
@Daniel-Hernandez-1 
As of this [commit](https://github.com/bradtaniguchi/GoTorosBank/commit/c3932f5655e29083ddf8a5f08e145e758e6ebacc) the PayBillsServlet currently parses the front-end AJAX call for the **amount**. This is unnecessary, as the amount is provided by the Bill itself. Go through the User that is returned from the database to verity the amount. You already grab the User object from the database to verity other data, use the object to verify the amount.

As of right now I will pass you only 2 things:
The **billID**
and the **accountID**
This should be the only information you need. 

With this issue we are getting a format issue when trying to look at the "amount" float. As such the PayBillServlet will not work until it is fixed.

**Comment by Daniel-Hernandez-1** [comment]
I believe this issue should now be resolved. I just pushed a commit right now. Please verify and close.

**Comment by bradtaniguchi** [comment]
The test is failing as of right now due to this:

Tests in error: 
  testPayBill(edu.csudh.goTorosBank.TestDatabaseInterface): java.util.Date cannot be cast to java.sql.Date

EDIT:
I added a new [import](https://github.com/bradtaniguchi/GoTorosBank/commit/fed3de832562a67bcccaa8443f0128ca6e685104), to get the java.util.date class, as it wasn't imported and you were using the java.sql.Date class, which is different.

We are getting a new Error, run the maven test goal to check your code....

**Comment by Daniel-Hernandez-1** [comment]
testPayBill() test now passed. I dont know how to use Maven.

**Comment by bradtaniguchi** [comment]
This functionality is fully implemented, requires more testing....
